source:
  host: localhost
  port: 1433
  database: StackOverflow2010
  user: sa
  password: "YourStrong@Passw0rd"
  schema: dbo
  trust_server_cert: true
  encrypt: false

target:
  host: localhost
  port: 5433
  database: stackoverflow
  user: postgres
  password: "PostgresPassword123"
  schema: public
  ssl_mode: disable

migration:
  workers: 4
  chunk_size: 100000
  target_mode: drop_recreate
  parallel_readers: 16
  parallel_writers: 8
